-- SQL файл для инициализации транзакций из ci_data.csv
-- Автоматически сгенерирован из первых 300 записей
-- Транзакции создаются для пользователя user@example.com (ID: 2)

-- Удаляем существующие транзакции пользователя (опционально)
-- DELETE FROM transactions WHERE user_id = 2;

DO $$
DECLARE
    target_user_id INTEGER := 2;
    transaction_count INTEGER := 0;
BEGIN
    -- Проверяем, что пользователь существует
    IF NOT EXISTS (SELECT 1 FROM users WHERE id = target_user_id) THEN
        RAISE EXCEPTION 'Пользователь с ID % не найден!', target_user_id;
    END IF;

    -- Вставляем транзакции
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Коммунальные услуги'::transactioncategory, 3950.00, 'Транзакция 1', '2023-01-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 105.00, 'Транзакция 2', '2023-03-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 55.00, 'Транзакция 3', '2023-03-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 56.00, 'Транзакция 4', '2023-03-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 1.00, 'Транзакция 5', '2023-03-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 6', '2023-03-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 500.00, 'Транзакция 7', '2023-04-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 1.00, 'Транзакция 8', '2023-04-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 500.00, 'Транзакция 9', '2023-04-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 28.00, 'Транзакция 10', '2023-10-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 149.00, 'Транзакция 11', '2023-10-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 10.00, 'Транзакция 12', '2023-10-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 1289.00, 'Транзакция 13', '2023-10-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 51.00, 'Транзакция 14', '2023-10-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 110.00, 'Транзакция 15', '2023-10-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 16', '2023-10-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 17', '2023-10-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 131.50, 'Транзакция 18', '2023-10-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 27.00, 'Транзакция 19', '2023-11-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 50.00, 'Транзакция 20', '2023-11-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 33.00, 'Транзакция 21', '2023-11-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 33.00, 'Транзакция 22', '2023-11-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 33.00, 'Транзакция 23', '2023-11-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 33.00, 'Транзакция 24', '2023-11-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 33.00, 'Транзакция 25', '2023-11-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 60.00, 'Транзакция 26', '2023-11-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 27', '2023-11-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 305.00, 'Транзакция 28', '2023-11-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 50.00, 'Транзакция 29', '2023-11-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 30', '2023-11-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 57.00, 'Транзакция 31', '2023-12-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 33.00, 'Транзакция 32', '2023-12-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 10.00, 'Транзакция 33', '2023-12-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 35.00, 'Транзакция 34', '2023-12-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 60.00, 'Транзакция 35', '2023-12-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 36', '2023-12-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 37', '2023-12-01'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 57.00, 'Транзакция 38', '2023-01-13'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 60.00, 'Транзакция 39', '2023-01-13'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 480.00, 'Транзакция 40', '2023-01-13'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 12.00, 'Транзакция 41', '2023-01-13'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 2000.00, 'Транзакция 42', '2023-01-13'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 120.00, 'Транзакция 43', '2023-01-13'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 50.00, 'Транзакция 44', '2023-01-13'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 200.00, 'Транзакция 45', '2023-01-13'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 15.00, 'Транзакция 46', '2023-01-13'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 47', '2023-01-14'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 48', '2023-01-14'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 173.75, 'Транзакция 49', '2023-01-14'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 25.00, 'Транзакция 50', '2023-01-14'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 50.00, 'Транзакция 51', '2023-01-14'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 52', '2023-01-14'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 10.00, 'Транзакция 53', '2023-01-14'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 54', '2023-01-14'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 110.00, 'Транзакция 55', '2023-01-15'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 35.00, 'Транзакция 56', '2023-01-15'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 200.00, 'Транзакция 57', '2023-01-15'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 58', '2023-01-15'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 59', '2023-01-15'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 155.24, 'Транзакция 60', '2023-01-15'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 25.00, 'Транзакция 61', '2023-01-15'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 12.00, 'Транзакция 62', '2023-01-16'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 33.00, 'Транзакция 63', '2023-01-16'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 29.00, 'Транзакция 64', '2023-01-16'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 50.00, 'Транзакция 65', '2023-01-16'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 60.00, 'Транзакция 66', '2023-01-16'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 32.00, 'Транзакция 67', '2023-01-16'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 68', '2023-01-16'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 37.00, 'Транзакция 69', '2023-01-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 272.00, 'Транзакция 70', '2023-01-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 70.00, 'Транзакция 71', '2023-01-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 72', '2023-01-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 85.00, 'Транзакция 73', '2023-01-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 74', '2023-01-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 75', '2023-01-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 10.00, 'Транзакция 76', '2023-01-18'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 33.00, 'Транзакция 77', '2023-01-18'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 78', '2023-01-18'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 60.00, 'Транзакция 79', '2023-01-18'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 80', '2023-01-18'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 81', '2023-01-18'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 120.00, 'Транзакция 82', '2023-01-19'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 130.00, 'Транзакция 83', '2023-01-19'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 84', '2023-01-19'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 12.00, 'Транзакция 85', '2023-01-19'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 25.00, 'Транзакция 86', '2023-01-19'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 55.00, 'Транзакция 87', '2023-01-19'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 10.00, 'Транзакция 88', '2023-01-20'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 42.00, 'Транзакция 89', '2023-01-20'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 90', '2023-01-20'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 91', '2023-01-20'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 92', '2023-01-20'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 500.00, 'Транзакция 93', '2023-01-21'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 42.00, 'Транзакция 94', '2023-01-21'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 80.00, 'Транзакция 95', '2023-01-21'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 96', '2023-01-21'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 25.00, 'Транзакция 97', '2023-01-21'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 200.00, 'Транзакция 98', '2023-01-21'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 99', '2023-01-21'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 200.00, 'Транзакция 100', '2023-01-21'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 2000.00, 'Транзакция 101', '2023-01-22'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 61.00, 'Транзакция 102', '2023-01-22'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 115.00, 'Транзакция 103', '2023-01-22'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 104', '2023-01-22'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 15.00, 'Транзакция 105', '2023-01-23'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 33.00, 'Транзакция 106', '2023-01-23'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 65.00, 'Транзакция 107', '2023-01-23'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 108', '2023-01-23'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 70.00, 'Транзакция 109', '2023-01-23'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 35.00, 'Транзакция 110', '2023-01-23'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 111', '2023-01-23'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 112', '2023-01-24'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 90.00, 'Транзакция 113', '2023-01-24'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 75.00, 'Транзакция 114', '2023-01-24'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 115', '2023-01-24'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 50.00, 'Транзакция 116', '2023-01-24'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 28.00, 'Транзакция 117', '2023-01-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Зарплата'::transactioncategory, 34800.00, 'Транзакция 118', '2023-01-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 65.00, 'Транзакция 119', '2023-01-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 27.00, 'Транзакция 120', '2023-01-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 121', '2023-01-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 10000.00, 'Транзакция 122', '2023-01-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 350.00, 'Транзакция 123', '2023-01-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 124', '2023-01-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 2.00, 'Транзакция 125', '2023-01-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 135.00, 'Транзакция 126', '2023-01-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 127', '2023-01-26'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 120.00, 'Транзакция 128', '2023-01-26'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Одежда'::transactioncategory, 1081.00, 'Транзакция 129', '2023-01-26'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 5000.00, 'Транзакция 130', '2023-01-26'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 299.00, 'Транзакция 131', '2023-01-26'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 2000.00, 'Транзакция 132', '2023-01-26'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 1000.00, 'Транзакция 133', '2023-01-26'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 5000.00, 'Транзакция 134', '2023-01-26'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 5000.00, 'Транзакция 135', '2023-01-26'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 163.28, 'Транзакция 136', '2023-01-26'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 24.00, 'Транзакция 137', '2023-01-27'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 288.00, 'Транзакция 138', '2023-01-27'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 70.00, 'Транзакция 139', '2023-01-27'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 72.00, 'Транзакция 140', '2023-01-27'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 7000.00, 'Транзакция 141', '2023-01-27'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 17500.00, 'Транзакция 142', '2023-01-27'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 143', '2023-01-27'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 80.00, 'Транзакция 144', '2023-01-27'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 145', '2023-01-28'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 146', '2023-01-28'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 1000.00, 'Транзакция 147', '2023-01-28'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 148', '2023-01-28'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 149', '2023-01-29'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 150', '2023-01-29'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 149.00, 'Транзакция 151', '2023-01-29'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 250.00, 'Транзакция 152', '2023-01-29'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 250.00, 'Транзакция 153', '2023-01-29'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 500.00, 'Транзакция 154', '2023-01-29'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 189.05, 'Транзакция 155', '2023-01-29'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 156', '2023-01-30'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 50.00, 'Транзакция 157', '2023-01-30'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 85.00, 'Транзакция 158', '2023-01-30'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 50.00, 'Транзакция 159', '2023-01-30'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 90.00, 'Транзакция 160', '2023-01-30'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 161', '2023-01-30'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 28.00, 'Транзакция 162', '2023-01-31'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 125.00, 'Транзакция 163', '2023-01-31'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 164', '2023-01-31'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 10000.00, 'Транзакция 165', '2023-01-31'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 154.44, 'Транзакция 166', '2023-01-31'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 167', '2023-01-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 168', '2023-01-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 80.00, 'Транзакция 169', '2023-01-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Коммунальные услуги'::transactioncategory, 5776.00, 'Транзакция 170', '2023-02-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 171', '2023-02-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 144.87, 'Транзакция 172', '2023-02-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 173', '2023-02-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 174', '2023-02-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 170.00, 'Транзакция 175', '2023-02-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 28.00, 'Транзакция 176', '2023-03-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 50.00, 'Транзакция 177', '2023-03-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 500.00, 'Транзакция 178', '2023-03-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 500.00, 'Транзакция 179', '2023-03-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 17.00, 'Транзакция 180', '2023-03-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 190.00, 'Транзакция 181', '2023-03-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 182', '2023-03-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 200.00, 'Транзакция 183', '2023-04-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 184', '2023-04-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 185', '2023-04-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 152.00, 'Транзакция 186', '2023-04-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 140.00, 'Транзакция 187', '2023-04-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 188', '2023-04-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 189', '2023-04-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 190', '2023-05-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 180.00, 'Транзакция 191', '2023-05-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 80.00, 'Транзакция 192', '2023-06-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 100.00, 'Транзакция 193', '2023-06-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 194', '2023-06-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 700.00, 'Транзакция 195', '2023-06-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 196', '2023-06-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 65.00, 'Транзакция 197', '2023-07-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 36.00, 'Транзакция 198', '2023-07-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 199', '2023-07-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 10.00, 'Транзакция 200', '2023-07-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 150.28, 'Транзакция 201', '2023-08-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 202', '2023-08-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 500.00, 'Транзакция 203', '2023-08-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 204', '2023-08-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 33.00, 'Транзакция 205', '2023-09-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 206', '2023-09-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Одежда'::transactioncategory, 474.00, 'Транзакция 207', '2023-09-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 32.00, 'Транзакция 208', '2023-09-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 209', '2023-09-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 210', '2023-10-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 54.00, 'Транзакция 211', '2023-10-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 51.00, 'Транзакция 212', '2023-10-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 60.00, 'Транзакция 213', '2023-10-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 39.00, 'Транзакция 214', '2023-10-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 215', '2023-10-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 52.00, 'Транзакция 216', '2023-10-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Одежда'::transactioncategory, 249.00, 'Транзакция 217', '2023-11-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Одежда'::transactioncategory, 225.00, 'Транзакция 218', '2023-11-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Одежда'::transactioncategory, 261.00, 'Транзакция 219', '2023-11-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 32.00, 'Транзакция 220', '2023-11-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 150.28, 'Транзакция 221', '2023-11-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 60.00, 'Транзакция 222', '2023-11-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 500.00, 'Транзакция 223', '2023-11-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 330.00, 'Транзакция 224', '2023-12-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 44.00, 'Транзакция 225', '2023-12-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 100.00, 'Транзакция 226', '2023-12-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 500.00, 'Транзакция 227', '2023-12-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 117.00, 'Транзакция 228', '2023-12-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 25.00, 'Транзакция 229', '2023-12-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 230', '2023-12-02'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 231', '2023-02-13'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 173.70, 'Транзакция 232', '2023-02-13'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 67.00, 'Транзакция 233', '2023-02-13'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 234', '2023-02-13'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 235', '2023-02-14'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 242.45, 'Транзакция 236', '2023-02-14'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 60.00, 'Транзакция 237', '2023-02-14'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 238', '2023-02-15'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 148.00, 'Транзакция 239', '2023-02-15'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 130.00, 'Транзакция 240', '2023-02-15'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 241', '2023-02-16'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 242', '2023-02-16'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 80.00, 'Транзакция 243', '2023-02-16'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 100.00, 'Транзакция 244', '2023-02-16'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 1500.00, 'Транзакция 245', '2023-02-16'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 5.00, 'Транзакция 246', '2023-02-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 247', '2023-02-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 248', '2023-02-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 65.00, 'Транзакция 249', '2023-02-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 250', '2023-02-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 70.00, 'Транзакция 251', '2023-02-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 50.00, 'Транзакция 252', '2023-02-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 475.00, 'Транзакция 253', '2023-02-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 254', '2023-02-17'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 10.00, 'Транзакция 255', '2023-02-18'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 60.00, 'Транзакция 256', '2023-02-18'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 257', '2023-02-18'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 70.00, 'Транзакция 258', '2023-02-18'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 259', '2023-02-18'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 150.50, 'Транзакция 260', '2023-02-19'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 136.00, 'Транзакция 261', '2023-02-19'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 8.00, 'Транзакция 262', '2023-02-19'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 67.00, 'Транзакция 263', '2023-02-19'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 100.00, 'Транзакция 264', '2023-02-19'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 265', '2023-02-19'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 266', '2023-02-20'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 500.00, 'Транзакция 267', '2023-02-20'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 65.00, 'Транзакция 268', '2023-02-20'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 269', '2023-02-20'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 45.00, 'Транзакция 270', '2023-02-20'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 33.00, 'Транзакция 271', '2023-02-21'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 272', '2023-02-21'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 273', '2023-02-21'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 50.00, 'Транзакция 274', '2023-02-21'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 35.00, 'Транзакция 275', '2023-02-21'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 6000.00, 'Транзакция 276', '2023-02-22'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 5500.00, 'Транзакция 277', '2023-02-22'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 50.00, 'Транзакция 278', '2023-02-22'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 35.00, 'Транзакция 279', '2023-02-22'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 50.00, 'Транзакция 280', '2023-02-22'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 42.00, 'Транзакция 281', '2023-02-22'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 282', '2023-02-23'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 283', '2023-02-23'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 400.00, 'Транзакция 284', '2023-02-23'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 30.00, 'Транзакция 285', '2023-02-23'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 286', '2023-02-23'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Зарплата'::transactioncategory, 34800.00, 'Транзакция 287', '2023-02-24'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 70.00, 'Транзакция 288', '2023-02-24'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 289', '2023-02-24'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 799.00, 'Транзакция 290', '2023-02-24'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 180.00, 'Транзакция 291', '2023-02-24'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 75.00, 'Транзакция 292', '2023-02-24'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 642.00, 'Транзакция 293', '2023-02-24'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 12.00, 'Транзакция 294', '2023-02-24'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 10000.00, 'Транзакция 295', '2023-02-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 140.00, 'Транзакция 296', '2023-02-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 20.00, 'Транзакция 297', '2023-02-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 10.00, 'Транзакция 298', '2023-02-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Продукты'::transactioncategory, 40.00, 'Транзакция 299', '2023-02-25'::date, NOW());
    transaction_count := transaction_count + 1;
    INSERT INTO transactions (user_id, category, amount, description, date, created_at) VALUES (target_user_id, 'Прочие расходы'::transactioncategory, 500.00, 'Транзакция 300', '2023-02-25'::date, NOW());
    transaction_count := transaction_count + 1;

    RAISE NOTICE 'Вставлено транзакций для пользователя %: %', target_user_id, transaction_count;
END $$;
